from flask import Flask, url_for, make_response
HelloApp = Flask(__name__)

@HelloApp.route('/')
def index():
    return 'This is index'

# @HelloApp.route('/hello')
def hello():
    msg = "Hello Word!!!!1"
    return msg

@HelloApp.route('/blog')
@HelloApp.route('/blog/<blog_no>')
def blog(blog_no=0):
    return 'This is blog number : '+ str(blog_no)

with HelloApp.test_request_context():
    print('1 : ', url_for('index'))
    print('2 : ', url_for('blog', blog_no = 'lkkiuy fer'))
    print('3 : ', url_for('blog', blog_no = 99, blog_name = 'nine nine'))

@HelloApp.route('/about')
def about():
    header = {
        'content-type' : 'application/json'
    }
    return make_response('This is response generated by make response',200,header)

HelloApp.add_url_rule('/hello','hello',hello)
# print('Flask(__name__) : ',__name__)
if __name__ == '__main__':
    HelloApp.run(host='0.0.0.0',port=5001, debug=True)